"""add flyer_pages table

Revision ID: 9360df64dedf
Revises: 210fa9f3d7a9
Create Date: 2026-08-28 19:24:24.871043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9360df64dedf'
down_revision: Union[str, Sequence[str], None] = '210fa9f3d7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flyer_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('brochure_id', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'brochure_id', 'page_number', name='uq_flyer_page')
    )
    with op.batch_alter_table('flyer_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flyer_pages_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flyer_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flyer_pages_store_id'))

    op.drop_table('flyer_pages')
    # ### end Alembic commands ###
