"""initial schema

Revision ID: 98dda1f76c86
Revises: 
Create Date: 2026-06-27 01:20:59.535707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98dda1f76c86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('plz', sa.String(length=8), nullable=False),
    sa.Column('market_code', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'plz', name='uq_store_chain_plz')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_chain'), ['chain'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_plz'), ['plz'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('category_path', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('regular_price_cents', sa.Integer(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=48), nullable=True),
    sa.Column('price_per_unit', sa.String(length=64), nullable=True),
    sa.Column('loyalty_note', sa.String(length=64), nullable=True),
    sa.Column('app_price_cents', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'external_id', name='uq_offer_store_ext')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_discount_pct'), ['discount_pct'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_store_id'))
        batch_op.drop_index(batch_op.f('ix_offers_source'))
        batch_op.drop_index(batch_op.f('ix_offers_discount_pct'))
        batch_op.drop_index(batch_op.f('ix_offers_category'))

    op.drop_table('offers')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_plz'))
        batch_op.drop_index(batch_op.f('ix_stores_chain'))

    op.drop_table('stores')
    # ### end Alembic commands ###
